@call cli ABMART 
@call cli ABMAUT 
@call cli ABMBAN 
@call cli ABMCLI 
@call cli ABMCOM 
@call cli ABMCTAS 
@call cli ABMDAT 
@call cli ABMDAT1 
@call cli ABMDEP 
@call cli ABMDES 
@call cli ABMEMP 
@call cli ABMFOR 
@call cli ABMIVA 
@call cli ABMMAR 
@call cli ABMPCON 
@call cli ABMPRO 
@call cli ABMREP 
@call cli ABMRET 
@call cli ABMRUB 
@call cli ABMVEN 
@call cli agenda 
@call cli BCAJA 
@call cli BUSQUEDA 
@call cli CalInfo 
@call cli CAMBIOPRE 
@call cli CANPAG 
@call cli CARCRE 
@call cli CARDEU 
@call cli CHEPRO 
@call cli CHETER 
@call cli cobran 
@call cli COMBUS 
@call cli COMPRAS 
@call cli COMPRAS1 
@call cli CONECTAR 
@call cli CONNTO 
@call cli DATOS 
@call cli DEMO 
@call cli DEPRET 
@call cli DESCU 
@call cli ETIQUE 
@call cli FACREM 
@call cli FACT 
@call cli FCAJA 
@call cli fe 
@call cli GASTOS 
@call cli GRAFICA 
@call cli HERRERO 
@call cli LISARTI 
@call cli LISCHE 
@call cli LISCOM 
@call cli lisdeu 
@call cli lisfac 
@call cli LISTADOSTAB 
@call cli LISVEN 
@call cli MODREM 
@call cli MODSTO 
@call cli ORDENES 
@call cli ORDPAG 
@call cli ORDPAG1 
@call cli PAGOS 
@call cli PREGEN 
@call cli PRELIS 
@call cli RCAJA 
@call cli RENDI 
@call cli REPORT 
@call cli RPREVIEW 
@call cli SAYTR 
@call cli setbrw 
@call cli tcalex 
@call cli TECLADO 
@call cli TIPDEP 
@call cli TRANSF 
@call cli USUA 
@call cli UTILES 
@call cli VENREI 
@call cli VENTAS 
@call cli VERCOMP 
@call cli xbrowse 
